# Generated by Django 5.2.7 on 2025-10-21 15:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название книги')),
                ('description', models.TextField(verbose_name='Описание книги')),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Обложка')),
                ('quantity_page', models.PositiveIntegerField(verbose_name='Количество страниц')),
                ('author', models.CharField(max_length=255, verbose_name='Писатель')),
                ('book_audio', models.URLField(blank=True, null=True, verbose_name='Ссылка на аудиокнигу (YouTube)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book')),
            ],
        ),
    ]
